# Render Threads自動化システム デプロイ設定
services:
  - type: web
    name: threads-automation
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: singapore
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: NODE_ENV
        value: production
      - key: DISPLAY
        value: ":99"
      - key: DEBIAN_FRONTEND
        value: noninteractive
      - key: RENDER
        value: "true"
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: threads-automation-disk
      mountPath: /app/data
      sizeGB: 1
    healthCheckPath: /status