# Render Threads自動化システム デプロイ設定
services:
  - type: web
    name: threads-automation
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: singapore
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: NODE_ENV
        value: production
      - key: DISPLAY
        value: ":99"
      - key: DEBIAN_FRONTEND
        value: noninteractive
      - key: RENDER
        value: "true"
      - key: JWT_SECRET
        value: threads-secret-key-2024-render-xyz789
      - key: SUPABASE_URL
        value: https://qjjnkclpqpybnnjswlhq.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqam5rY2xxcXB5Ym5uanN3bGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NjEyNzYsImV4cCI6MjA1MzIzNzI3Nn0.RLZ5Uh7xVWWl6w-WJc1Ni_CgbXRdB_qGGnZmO8Qx7R4
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqam5rY2xxcXB5Ym5uanN3bGhxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNzY2MTI3NiwiZXhwIjoyMDUzMjM3Mjc2fQ.aZ2Q8hP9YvJKIR1C_4WrX6S3LjKvM9B5Fn0Hq7Rt2Ew
      - key: CHROME_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: threads-automation-disk
      mountPath: /app/data
      sizeGB: 1
    healthCheckPath: /status